### ISSUE TITLE
Question regarding 3D JPS

### ISSUE THREAD

**Issue by samuellai1133** [LenaShengzhen/AerialRobotics#3]
Hi, Firstly i would like to say that your implementation of JPS in 3D world is great!
I would like to request if you have any write up on how you implemented the JPS in 3D world?
Thanks, and best regards.

**Comment by LenaShengzhen** [comment]
As far as I know, there is such a paper of 3D-JPS: "JPS Algorithm Adaptation and Optimization to Three-dimensional Space". 
I won't comment on it because I haven't read it.
Hope it helps you.

**Comment by LenaShengzhen** [comment]
A small part of how to implement of 3D-JPS has been written in my thesis, but this thesis has not been published yet.

**Comment by samuellai1133** [comment]
Thank you for your reply. Best wishes for your Thesis.
