### ISSUE TITLE
Question about JPS-3D

### ISSUE THREAD

**Issue by HangX-Ma** [LenaShengzhen/AerialRobotics#5]
Hi, Lena. I have read the JPS part of your paper, _TRAJECTORY PLANNING BASED ON OPTIMIZED JUMP POINT SEARCH RESULTS USING ARTIFICIAL POTENTIAL FIELD IN 3-D ENVIRONMENTS_. In this part, you explain the situation about the straight move in 3D space of JPS. It's understandable and clear. I have read a similar paper, _JPS Algorithm Adaptation and Optimization to Three-dimensional Space_ written by Pertti Ranttila and Kesäkuu. 2019, who explains the one-axis, two-axis, three-axis situations. But I was confused by some question when I wanted to calulate the **natural neighbor** in two-axis situation. 
In  _JPS Algorithm Adaptation and Optimization to Three-dimensional Space_ 
![two-axis.png](https://s2.loli.net/2021/12/22/9zVlTZkiRGBOAIf.png)
In _Planning Dynamically Feasible Trajectories for Quadrotors using Safe Flight Corridors in 3-D Complex Environments_
![two-axis2.png](https://s2.loli.net/2021/12/22/lRme731whZoy54s.png)
They all prune the top layer and bottom layer in the 3x3 cubic in two-axis situation. However, according to the definition of the **natural neighbor**, 

**Straight Moves:** <img src="http://chart.googleapis.com/chart?cht=tx&chl= len(<p(x),...,n>\\x)<=len(<p(x),x,n>) " style="border:none;">
**Diagonal Moves:**<img src="http://chart.googleapis.com/chart?cht=tx&chl= len(<p(x),...,n>\\x)<len(<p(x),x,n>) " style="border:none;">

I found that start from the grey voxel, the cost that I go through the blue voxel and reach the voxel whose cost is sqrt(3) (you can image the corner voxels at the top or bottom layer) is the same as the cost that I go through the voxel that is direct above or below the blue voxel and reach the corner voxels. Why  those two voxels cannot be the **natural neighbor** ? Those two voxels cannot be pruned according to the pruning policy (If my assumption is correct).
![two-axis3.png](https://s2.loli.net/2021/12/22/ZD3hI8H2gjpoVFt.png)

**Comment by HangX-Ma** [comment]
@LenaShengzhen

**Comment by LenaShengzhen** [comment]
Good Question.

I haven't read "JPS Algorithm Adaptation and Optimization to Three-dimensional Space".

For your screenshots from this paper, the results of this formula of diagonal direction are contradictory to the results of the screenshots in this paper. I think you could send email to the author asking about this question and to find whether the diagonal formula of 3D-JPS has changed compared with 2D-JPS, or we miss something.

**Comment by HangX-Ma** [comment]
Thanks a lot for your answer. 
After reading the code in [KumarRobotics/jps3d](https://github.com/KumarRobotics/jps3d) , I figured out that more rules should be added to explain the expanding situations in 3D space. I'm trying to explain those special situations.
I will close this issue and hope others can get help from `jps3d`.
